apiVersion: hub.kalypso.io/v1alpha1
kind: DeploymentDescriptor
metadata:
  name: hello-world-$DEPLOYMENT_TARGET
  labels:
    config-revision: $CONFIG_REVISION
spec:
  workload:
    name: busybox
    source:
        repo: https://github.com/$SOURCE_REPO
        branch: $SOURCE_BRANCH
        path: .
    application:
        name: $APPLICATION
        workspace:
            name: kaizen-team
  deploymentTarget:
    name: $DEPLOYMENT_TARGET
    environment: $ENVIRONMENT
    manifests:
        repo: https://github.com/eedorenko/configuratix-gitops
        branch: $ENVIRONMENT
        path: $DEPLOYMENT_TARGET_MANIFESTS_PATH
  workloadVersion:
    version: $VERSION
    commit: $SRC_COMMIT