apiVersion: hub.kalypso.io/v1alpha1
kind: DeploymentDescriptor
metadata:
  name: $WORKLOAD-$DEPLOYMENT_TARGET
spec:
  workload:
    name: hw
    source:
        repo: https://github.com/$SOURCE_REPO
        branch: $SOURCE_BRANCH
        path: .
    application:
        name: hello-world
        workspace:
            name: kaizen-team
  deploymentTarget:
    name: $DEPLOYMENT_TARGET
    environment: $ENVIRONMENT
    manifests:
        repo: https://github.com/$GITOPS_REPO
        branch: $ENVIRONMENT
        path: $DEPLOYMENT_TARGET_MANIFESTS_PATH
  workloadVersion:
    version: $VERSION
    commit: $SRC_COMMIT    