apiVersion: scheduler.kalypso.io/v1alpha1
kind: Workload
metadata:
  name: hw
  labels:
    type: application
spec:
  deploymentTargets:
    - name: dev-gray
      labels:
        purpose: functional-test
        zone: gray
        application: hello-world
      environment: dev
      manifests:
        repo: https://github.com/eedorenko/hello-world-gitops
        branch: dev-gray
        path: ./hw
    - name: dev-green
      labels:
        purpose: functional-test
        zone: green
        application: hello-world
      environment: dev
      manifests:
        repo: https://github.com/eedorenko/hello-world-gitops
        branch: dev-green
        path: ./hw
    - name: dev-red
      labels:
        purpose: functional-test
        zone: red
        application: hello-world
      environment: dev
      manifests:
        repo: https://github.com/eedorenko/hello-world-gitops
        branch: dev-red
        path: ./hw    
    - name: stage-gray
      labels:
        purpose: uat-test
        zone: gray
        application: hello-world
      environment: stage
      manifests:
        repo: https://github.com/eedorenko/hello-world-gitops
        branch: stage-gray
        path: ./hw
    - name: stage-green
      labels:
        purpose: uat-test
        zone: green
        application: hello-world
      environment: stage
      manifests:
        repo: https://github.com/eedorenko/hello-world-gitops
        branch: stage-green
        path: ./hw
    - name: stage-red
      labels:
        purpose: uat-test
        zone: red
        application: hello-world
      environment: stage
      manifests:
        repo: https://github.com/eedorenko/hello-world-gitops
        branch: stage-red
        path: ./hw             
