apiVersion: scheduler.kalypso.io/v1alpha1
kind: Workload
metadata:
  name: hw
  labels:
    type: application
spec:
  deploymentTargets:
    - name: dev
      labels:
        purpose: dev-test
        application: hello-world
      environment: dev
      manifests:
        repo: https://github.com/eedorenko/hello-world-gitops
        branch: dev
        path: ./hw
    - name: functional-test-stage
      labels:
        purpose: functional-test
        application: hello-world
      environment: stage
      manifests:
        repo: https://github.com/eedorenko/hello-world-gitops
        branch: stage
        path: ./functional
    - name: performance-test-stage
      labels:
        purpose: performance-test
        application: hello-world
      environment: stage
      manifests:
        repo: https://github.com/eedorenko/hello-world-gitops
        branch: stage
        path: ./performance
    - name: prod-gray
      labels:
        purpose: prod
        zone: gray
      environment: prod
      manifests:
        repo: https://github.com/eedorenko/hello-world-gitops
        branch: prod-gray
        path: ./hw
    - name: prod-green
      labels:
        purpose: prod
        zone: green
      environment: prod
      manifests:
        repo: https://github.com/eedorenko/hello-world-gitops
        branch: prod-green
    - name: prod-red
      labels:
        purpose: prod
        zone: red
      environment: prod
      manifests:
        repo: https://github.com/eedorenko/hello-world-gitops
        branch: prod-red
