apiVersion: scheduler.kalypso.io/v1alpha1
kind: Workload
metadata:
  name: hello-world-app
  labels:
    type: application
spec:
  deploymentTargets:
    - name: functional-test-dev-gray-east-us
      labels:
        purpose: functional-test-east-us
        location: east-us
        zone: gray
        application: hello-world
      environment: dev
      manifests:
        repo: https://github.com/eedorenko/hello-world-gitops
        branch: dev-gray
        path: ./functional-test/east-us
    - name: functional-test-dev-gray-west-us
      labels:
        purpose: functional-test-west-us
        location: west-us        
        zone: gray
        application: hello-world
      environment: dev
      manifests:
        repo: https://github.com/eedorenko/hello-world-gitops
        branch: dev-gray
        path: ./functional-test/west-us
    - name: functional-test-dev-green
      labels:
        purpose: functional-test
        zone: green
        application: hello-world
      environment: dev
      manifests:
        repo: https://github.com/eedorenko/hello-world-gitops
        branch: dev-green
        path: ./functional-test
    - name: functional-test-dev-red
      labels:
        purpose: functional-test
        zone: red
        application: hello-world
      environment: dev
      manifests:
        repo: https://github.com/eedorenko/hello-world-gitops
        branch: dev-red
        path: ./functional-test
    
    - name: uat-test-stage-gray
      labels:
        purpose: uat-test
        zone: gray
        application: hello-world
      environment: stage
      manifests:
        repo: https://github.com/eedorenko/hello-world-gitops
        branch: stage-gray
        path: ./uat-test
    - name: uat-test-stage-green
      labels:
        purpose: uat-test
        zone: green
        application: hello-world
      environment: stage
      manifests:
        repo: https://github.com/eedorenko/hello-world-gitops
        branch: stage-green
        path: ./uat-test
    - name: uat-test-stage-red
      labels:
        purpose: uat-test
        zone: red
        application: hello-world
      environment: stage
      manifests:
        repo: https://github.com/eedorenko/hello-world-gitops
        branch: stage-red
        path: ./uat-test              
