name: Ensure Plant Chat UI

on:
  pr:
    branches: ["main"]


jobs:
  Build_Push_Image:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
    - name: Checkout Source
      uses: actions/checkout@v3
